### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/doc2sim#2]
It would be great to support the application with a neat GUI built using Flask (since its a pretty simple script with no heavy backend). Looking for contributions towards this!

**Comment by andidevel** [comment]
Hi @aditeyabaral. I would like to help on this issue.

So, what do you have in mind? A separated script, or something like:
```bash
python3 d2v.py --gui
```
That start a Flask app and launch default browser?

**Comment by aditeyabaral** [comment]
Yup, that would be nice.

**Comment by andidevel** [comment]
Hi @aditeyabaral, the feature is not finished yet, but if you want to see a preview, checkout my branch [feature/gui-flask](https://github.com/andidevel/doc2sim/tree/feature/gui-flask), install the requirements (Flask), run:
```bash
python3 d2v.py --gui
```
And open your browser on:

http://localhost:3000

In the text box, write the **absolute path** of a file, press **Add**. Add many files you want and press **Check** to get the similarity matrix.

It's a working in progress. A local file browser, to help add files to compare, is missing, and some validations as well.

**Comment by aditeyabaral** [comment]
Just checked it out, it looks great!
Maybe could you add "Doc2Sim" as a header on the page? Everything else looks neat!
